### ISSUE TITLE
add detach flag to AddOnion

### ISSUE THREAD

**Issue by mischief** [Yawning/bulb#3]
i'm sure you're familiar, but this is so i can call DeleteOnion on a different control port connection.

**Comment by unkaktus** [comment]
FIY I've added support for this in #8.

**Comment by unkaktus** [comment]
Implemented in 3cc4ebc379bcc60ecff44995a40b5cf9ed4844bb.

**Comment by Yawning** [comment]
Closing, since this is basically fixed.
